### ISSUE TITLE
Use text-transform: uppercase

### ISSUE THREAD

**Issue by okonet** [YGLF-Kyiv/website-2018#47]
At the moment, titles are typesetted with ALL CAPS. This is a big accessibility issue since screen readers will read each letter separately. It's also not possible to copy-paste text without reformatting it.

In CSS, you can add `text-transform: uppercase` to achieve the same presentation without having to change the semantics of HTML.

**Comment by marina-marina** [comment]
@okonet 
I have fixed the cases that I've found (we've missed out a couple of buttons) but I couldn't find any titles in ALL CAPS. Our titles like the green one and the white one look like this:
![image](https://user-images.githubusercontent.com/2051028/38662592-84a454b8-3e3d-11e8-85e2-44bacba14f61.png)

Could you please elaborate on which titles you meant?
Thank you!

**Comment by okonet** [comment]
Sure! ![](https://www.dropbox.com/s/p1688guoe5loru1/IMG_1302.JPG?dl=0)

**Comment by okonet** [comment]
Back to my computer ¯\_(ツ)_/¯

Sorry for not being clear. Here is the link: http://yglf.com.ua/schedule

![2018-04-12 at 14 58](https://user-images.githubusercontent.com/11071/38678673-fb409374-3e61-11e8-8342-b5609b6f7015.png)

**Comment by tyv** [comment]
@okonet thanks for issue, but I don't see this
![2018-04-12_17-45-18](https://user-images.githubusercontent.com/122360/38684870-5992110c-3e79-11e8-8d1e-1f2019788ecf.png)

**Comment by okonet** [comment]
Interesting. Looks like it the clipboard problem then? I have been trying to copy and paste it and it was uppercase.

**Comment by marina-marina** [comment]
I think it's because it's an anchor link. When you click on  link the native behavior is going to the address in href. Therefore, you can't double click on those titles to select them.

**Comment by okonet** [comment]
I didn’t mean double clicking but a regular selection and copy and paste somewhere

**Comment by tyv** [comment]
> I have been trying to copy and paste it and it was uppercase.

@okonet it is browser default behaviour https://codepen.io/tyv/pen/aYrVzm

**Comment by okonet** [comment]
Yeah I realized it. Sorry for the noise
